export enum ActionTypes {
  GET_LESSON = "GET_LESSON",
  GET_LESSON_SUCCESS = "GET_LESSON_SUCCESS",
  GET_LESSON_FAILURE = "GET_LESSON_FAILURE",
  UPDATE_ANSWER = "UPDATE_ANSWER",
  HANDLE_PAGE_SUBMIT = "HANDLE_PAGE_SUBMIT",
  CLEAR_LESSON = "CLEAR_LESSON"
}
